site: JS
url: #yoururl
title: JS
description: Personal site
twitter:
  username: jerrysun_
  card: summary
  creator: #yourusername
author:
  twitter: jerrysun_
  name: #yourusername
  avatar:
  email: #youremail
  url: www.jerrysun.me
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  collections_dir: pages
  pages:
    output: true
    permalink: /:name
  writings:
    output: true
    permalink: /:year/:month/:day/:slug
  travels:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
